### ISSUE TITLE
on at least one Mac, qtj:camera-start fails the first time, succeeds the second

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/QTJ-Extension#1]
On my MacBook Pro running Lion, `qtj:camera-start` fails on first call (error below), succeeds when I try it a second time (without restarting NetLogo or reopening the model, I just press the start button in QuickTime Camera Example a second time).

Though the first call fails with an error, it does cause the green light by my camera to turn on and stay on.

It's 100% reproducible on my laptop in both NetLogo 4.1.3 and 5.0, but when I tried one of the iMacs in the lab running Lion, it always worked the first time.

``` text

Extension exception: Failed to open a session.  QuickTime may not be installed properly. Or your camera may not be connected or on.
error while observer running QTJ:CAMERA-START
  called by Button 'start'

org.nlogo.nvm.EngineException: Extension exception: Failed to open a session.  QuickTime may not be installed properly. Or your camera may not be connected or on.
 at org.nlogo.extensions.qtj.Capture$StartCamera.perform(Capture.java:66)
 at org.nlogo.prim._extern.perform(_extern.java:54)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.0RC10
Java HotSpot(TM) Client VM 1.6.0_29 (Apple Inc.; 1.6.0_29-b11-402-11D50)
operating system: Mac OS X 10.7.3 (i386 processor)
model: QuickTime Camera Example
```

**Comment by SethTisue** [comment]
(repo is moribund)
